FROM tomcat:7-jre8

ADD https://s3.eu-central-1.amazonaws.com/docker-mk-mar-2017/module4/jpetstore.war /usr/local/tomcat/webapps/jpetstore.war
COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
